### ISSUE TITLE
Error with the gather_keys_oauth2.py script

### ISSUE THREAD

**Issue by deep-introspection** [orcasgit/python-fitbit#122]
I run the gather_keys_oauth2.py script with my client_id and client_secret but got this error:

```
Traceback (most recent call last):
  File "gather_keys_oauth2.py", line 81, in <module>
    server.browser_authorize()
  File "gather_keys_oauth2.py", line 36, in browser_authorize
    url, _ = self.fitbit.client.authorize_token_url()
ValueError: too many values to unpack
```

Any idea where it can come from?

**Comment by LEXmono** [comment]
Can you provide more details?  Maybe what you are running, but please redact your personal information. 

It sounds like something is being added to self.fitbit.client.authorize_token_url(), which doesn't make sense as the script is written.
