### ISSUE TITLE
fitbit.exceptions.HTTPServerError when setting alarm.

### ISSUE THREAD

**Issue by jacksonsevendelta** [orcasgit/python-fitbit#124]
I'm getting an exception from python with the following code:
```
reccurance = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']

device_id = '123456789' # In the actual program this is a real device ID

fb.add_alarm(device_id, alarm_time, reccurance, recurring=False, enabled=True, label='Find Device Alarm', snooze_length=None, snooze_count=None, vibe='DEFAULT')
```
I've checked datetime formats and everything, but it still gives me the following output:
```
Traceback (most recent call last):
  File "PATH\TO\MY\PROGRAM\main.py", line 29, in <module>
    fb.add_alarm(device_id, alarm_time, reccurance, recurring=False, enabled=True, label='Find Device Alarm', snooze_length=None, snooze_count=None, vibe='DEFAULT')
  File "C:\Users\somebody\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fitbit\api.py", line 716, in add_alarm
    return self.make_request(url, data=data, method="POST")
  File "C:\Users\somebody\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fitbit\api.py", line 223, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "C:\Users\somebody\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fitbit\api.py", line 99, in make_request
    exceptions.detect_and_raise_error(response)
  File "C:\Users\somebody\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fitbit\exceptions.py", line 94, in detect_and_raise_error
    raise HTTPServerError(response)
fitbit.exceptions.HTTPServerError: An error occurred with the Fitbit Web API while processing the request. Error id: A29E0282:7651_A92D91CB:01BB_59D3331F_4A63FA7:3D47
```
Any help with this? My program is just to set an alarm 20 seconds after the current time.

**Comment by LEXmono** [comment]
You are not including the timezone in your request. Per the [code](https://github.com/orcasgit/python-fitbit/blob/9a3a599862328dd620a848d86f1ddf932592532b/fitbit/api.py#L722), alarm_time should be a timezone aware datetime object. 

You can do this with another module called pytz. 

> import pytz
> 
> tz = pytz.timezone("US/Eastern")
> alarm_time = datetime.datetime(2017, 10, 21, 16, 0)
> alarm_time = tz.localize(alarm_time, is_dst=None)
> 
> reccurance = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']
> device_id = '########' # In the actual program this is a real device ID
> client.add_alarm(device_id, alarm_time, reccurance, recurring=False, enabled=True, label='Find Device Alarm', snooze_length=None, snooze_count=None, vibe='DEFAULT')
> 
> 
> 
> {'trackerAlarm': {'alarmId': ##########,
>   'deleted': False,
>   'enabled': True,
>   'label': 'Find Device Alarm',
>   'recurring': False,
>   'snoozeCount': 1,
>   'snoozeLength': 9,
>   'syncedToDevice': False,
>   'time': '16:00-04:00',
>   'vibe': 'DEFAULT',
>   'weekDays': []}}

**Comment by jacksonsevendelta** [comment]
Thank you for this.
