### ISSUE TITLE
Is the Quickstart example still working?

### ISSUE THREAD

**Issue by wshayes** [orcasgit/python-fitbit#15]
I tried to run:

    import fitbit
    def main():
        consumer_key = 'xxx'  # key and secret collected from dev.fitbit.com site
        consumer_secret = 'xxx'
        unauth_client = fitbit.Fitbit(consumer_key, consumer_secret)
        print unauth_client.activities()

And got (with the 0.0.2 release as installed using pip today on a Mac Mavericks machine):
Traceback (most recent call last):
  File "./fb.py", line 27, in <module>
    main()
  File "./fb.py", line 23, in main
    print unauth_client.activities()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fitbit/utils.py", line 38, in _curried
    return _curried_func(*(args+moreargs), **dict(kwargs, **morekwargs))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fitbit/api.py", line 297, in _COLLECTION_RESOURCE
    return self.make_request(url, data)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fitbit/api.py", line 201, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fitbit/api.py", line 73, in make_request
    raise HTTPBadRequest(response)
fitbit.exceptions.HTTPBadRequest

I also tried to run the authorized example and also got the HTTPBadRequest.

Thanks!

**Comment by brad** [comment]
@wshayes OK, this is not a bug. To create an authenticated client you need to provide the `resource_owner_key` and `resource_owner_secret` as well as the consumer key and secret. The following works:
```python
auth_client = fitbit.Fitbit(consumer_key, consumer_secret, resource_owner_key=resource_owner_key, resource_owner_secret=resource_owner_secret)
auth_client.activities()
```
Please reopen if there is a problem.

**Comment by brad** [comment]
Sorry, premature closure. I think the real problem here is that `activities` is not a method that can be used without authentication, though the `python-fitbit` docs clearly make it seem that way.

**Comment by avinash-keshri** [comment]
@wshayes : Are you able to get the 'user_key' and 'user_secret' via './fitbit/gather_keys_cli.py' to be used in below code:

authd_client = fitbit.Fitbit('consumer_key', 'consumer_secret', resource_owner_key='user_key', resource_owner_secret='user_secret')

If yes, can you pls tell me the steps to fetch those. Thanks in advance.
