### ISSUE TITLE
getting missing access token parameter  trying to refresh token

### ISSUE THREAD

**Issue by pedrobpio** [orcasgit/python-fitbit#94]
Hi,
I'm having  an issue here, it might be because I'm a newbie at OAuth and python, or because I'm doing something wrong here, but anyway.
I'm trying to refresh my token and I'm getting the following message:

    authd_client.client.refresh_token()
  File "C...Python\Python35-32\lib\site-packages\fitbit\api.py", line 162, in refresh_token
    auth=requests.auth.HTTPBasicAuth(self.client_id, self.client_secret)
  File "C...\Python\Python35-32\lib\site-packages\requests_oauthlib\oauth2_session.py", line 301, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C...\Python\Python35-32\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 409, in parse_request_body
_response
    self.token = parse_token_response(body, scope=scope)
  File "C...\Programs\Python\Python35-32\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 376, in parse_token_response

    validate_token_parameters(params)
  File "C...\Python\Python35-32\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 386, in validate_token_param
eters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

and this is how I'm trying:

authd_client = fitbit.Fitbit("ID", 'secret',
                             access_token=ACCESS_TOKEN, refresh_token=REFRESH_TOKEN)

authd_client.client.refresh_token()

I would like to know if it is a bug or what is my mistake here.
Thanks

**Comment by pedrobpio** [comment]
So sorry, it was my mistake, there is nothing wrong with this part of the API, I wasn't passing the refresh token correctly.

**Comment by cedricbonhomme** [comment]
Hi @pedrobpio,

I am using the fitbit module in order to retrieve my data and to plot it with matplotlib (https://github.com/cedricbonhomme/health). It's working quite well. but now I have to renew the access token.

I am experiencing the same problem. Could you please show how you are passing the refresh token?

My code:

```python
client_kwargs = {
        'client_id': CLIENT_KEY,
        'client_secret': CLIENT_SECRET,
        'callback_uri': 'https://dev.fitbit.com',
        'scope': ['sleep+settings+nutrition+activity+social+heartrate+profile+weight+location']
}
client_kwargs['access_token'] = ACCESS_TOKEN
client_kwargs['refresh_token'] = REFRESH_TOKEN

fb = fitbit.Fitbit(CLIENT_KEY, CLIENT_SECRET, oauth2=True, access_token=ACCESS_TOKEN, refresh_token=REFRESH_TOKEN)
#fb = fitbit.Fitbit(**client_kwargs)
retval = fb.client.refresh_token()
```

And so I get:

```bash
$ python3.5 refresh_token.py 
Traceback (most recent call last):
  File "refresh_token.py", line 33, in <module>
    retval = fb.client.refresh_token()
  File "/usr/local/lib/python3.5/site-packages/fitbit/api.py", line 163, in refresh_token
    auth=requests.auth.HTTPBasicAuth(self.client_id, self.client_secret)
  File "/usr/local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

I do not see a fundamental difference with https://github.com/pedrobpio/demo-python-fitbit/blob/master/demo-2.py#L101 . 


Concerning your variable `userid = f.readline()` (https://github.com/pedrobpio/demo-python-fitbit/blob/master/demo-2.py#L95), why don't you use the one stored in config.ini ? Does the client_id (the _OAuth 2.0 Client ID_) change? 



thanks,


Cédric

**Comment by brad** [comment]
@cedricbonhomme We are also on gitter if you want to ask there

**Comment by cedricbonhomme** [comment]
Thanks, I'll meet you on gitter!

**Comment by pedrobpio** [comment]
hi Cedric, 
Answering your question, the clientID doesn’t change, in my code I just used the same name for the OAuth 2.0 client ID (USER_ID) and the id from the user that I'm retrieving the data(userid), in this case the one used to do the connection with OAuth is the USER_ID (the one in config.ini). The one from the line 95 (userid) will probably have no use for you.

In my code that you found (sorry for the lack of documentation) The demo2.py (the one that you quote) utilize documents from the demo.py. At demo.py I generate the first authorization and save the data into a file for later do the refresh, in this file I get the refresh data (ACCESS_TOKEN and REFRESH_TOKEN) and pass for the authd_client. later doing the refresh with authd_client.client.refresh_token().

if you are passing the data correctly there is no reason for the refresh not to work, check if you are passing the ACCESS_TOKEN and REFRESH_TOKEN correctly and remember that when you do the refresh token once you will generate a different ACCESS_TOKEN and REFRESH_TOKEN that are the one you should use next time you will need to refresh the token.

hope I have helped

**Comment by cedricbonhomme** [comment]
thanks for your response. I do not know what I am doing wrong.
Anyway, thank you. We're discussing about that on gitter.

**Comment by cedricbonhomme** [comment]
Hello @pedrobpio ,

I just testes to renew my new access token (which expired this morning) with something similar to your code:
https://github.com/cedricbonhomme/health/blob/62813f42cb558ee370cc338e72ccd19b31180cbe/refresh_token.py#L30

I still have the same problem:

```bash
$ python3.5 refresh_token.py 
Traceback (most recent call last):
  File "refresh_token.py", line 24, in <module>
    retval = fb.client.refresh_token()
  File "/usr/local/lib/python3.5/site-packages/fitbit/api.py", line 163, in refresh_token
    auth=requests.auth.HTTPBasicAuth(self.client_id, self.client_secret)
  File "/usr/local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by cedricbonhomme** [comment]
but I am able to renew the access token (and get a new refresh token) with the script **gather_keys_oauth2.py**.
